POST http://localhost:8080/apis/graphs/unweighted/BFS
Content-Type: application/json

{
    "vertex_count": 3,
    "neighbors": [
        [2,3],
        [3,1],
        [1,2]
    ],
    "start_vertex": 1
}